name: Deployment

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: executing remote ssh commands using password
                uses: appleboy/ssh-action@v1.0.0
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    script: |
                        cd /var/www/lastframe &&
                        git fetch --all &&
                        git reset --hard origin/master &&
                        docker compose up -d --build &&
                        chmod +x ./deploy.sh &&
                        docker exec game_php /bin/sh -c "./deploy.sh"